apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: cns-ubiwhere
    repository: jenkins-x-github
  - key: staging
  - key: production
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsenc-prod
      kubernetes.io/ingress.class: nginx
    domain: jx.snob.ubiwhere.com
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: admin@snob.ubiwhere.com
      enabled: false
      production: false
  pipelineUser:
    username: cns-ubiwhere
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
